export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  OWNER = 'ROLE_OWNER',
  PRINCIPAL = 'ROLE_PRINCIPAL',
  SECRETARY = 'ROLE_SECRETARY',
  STUDENT = 'ROLE_STUDENT',
  TEACHER = 'ROLE_TEACHER',
  TREASURER = 'ROLE_TREASURER',
}
